
- hosts: node1 
  roles:
    - part1
  post_tasks:
  - name: Get Service Facts
    service_facts:
  - name:
    debug:
      msg:
      - "Service HTTPD Running"
    when: ansible_facts.services["httpd.service"]['state'] == 'running'
