- name: Edit grub file 
  hosts: node1 
  tasks:
  - name: Add config
    lineinfile:
      path: /etc/default/grub
      regexp: '^(GRUB_CMDLINE_LINUX=(?!.* net.ifnames=0 biosdevname=0)\"[^\"]+)(\".*)' 
      line: '\1 net.ifnames=0 biosdevname=0\2'
      backrefs: yes
    notify:
      - grub2-mkconfig
  handlers:
    - name: grub2-mkconfig
      shell: grub2-mkconfig    
