---
# tasks file for part1
- name: Install Apache
  yum:
    name:
    - httpd
    state: present
    update_cache: yes
  notify:
    - restart_httpd
- name: Add Index.html
  template:
    src: index.html.j2 
    dest: /var/www/html/index.html
- name: Enabled Port
  firewalld:
    port: 80/tcp
    permanent: true
    state: enabled
  notify:
    - reloaded_firewalld
